### ISSUE TITLE
Application unable to reconnect to CloudSQL after instance maintenance

### ISSUE THREAD

**Issue by devillexio** [GoogleCloudPlatform/cloudsql-proxy#400]
## Bug Description

When our CloudSQL instance performs maintenance that interrupts existing connections, our application cannot connect via the proxy until we restart the proxy container.
## How to reproduce

Unfortunately, I'm not sure how to reproduce this as it seems to only happen when our CloudSQL instance performs maintenance that severs existing connections, and prevents further connectivity until we restart the cloudsql-proxy sidecar container (by restarting the pod).

## Environment

- application
    - image node:lts-slim; currently node v12.17.0 (npm v6.14.4)
     - database driver: sidorares/node-mysql2 (v2.1.0)
     - We have both uncaughtException and unhandledRejection for the node process, and both of these result in a process exit, and container restart, after logging the error.
- cloudsql-proxy
     - image: gcr.io/cloudsql-docker/gce-proxy:1.16
     - sidecar to application
- CloudSQL instance (Second Generation) hosted in GCE

**Comment by kurtisvg** [comment]
Additional context in https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/147#issuecomment-637848910. 

It's possible this could be replicated by connecting to an instance with high availability and performing a failover.

**Comment by kurtisvg** [comment]
Additional thoughts on resolution: 

This might be when the failover occurs, the secondary VM might have a different server cert and a new client ephemeral cert needs to be generated. I think this is an issue that we addressed in the Java connector by retrying a refresh when a connection attempt failed. Something similar should probably be done here, but might be fairly intensive to rework the connection logic.

**Comment by orjanbruland** [comment]
We experienced the same issue yesterday when using cloudsql-proxy as a Go library. After an automatic update of our PostgreSQL instance services started to fail with a `tls: bad certificate` error. The issue persisted until the cached certificate expired and got replaced by a new one.
